plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.144'
    id 'org.jetbrains.kotlin.jvm' version '2.4.10'
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

sourceSets.main.resources {
    srcDir('src/generated/resources')
}

repositories {
    mavenCentral()
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)
kotlin {
    jvmToolchain(21)
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

neoForge {
    enable {
        version = project.neo_version
        disableRecompilation = true
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        configureEach {
            logLevel = org.slf4j.event.Level.INFO
            jvmArguments.addAll '-Xms128M', '-Xmx448M', '-XX:MaxMetaspaceSize=192m'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    jarJar "org.jetbrains.kotlin:kotlin-stdlib:2.4.10"

    compileOnly files("libs/tacz-1.1.8+neoforge.1.21.11.r0.jar")
    compileOnly files("libs/yet-another-config-lib-v3-3.8.2+1.21.11-neoforge.jar")
    compileOnly files("libs/sound-physics-remastered-neoforge-1.21.11-1.5.1.jar")
    compileOnly files("libs/commons-math3-3.6.1.jar")

    localRuntime files("libs/tacz-1.1.8+neoforge.1.21.11.r0.jar")
    localRuntime files("libs/yet-another-config-lib-v3-3.8.2+1.21.11-neoforge.jar")
    localRuntime files("libs/sound-physics-remastered-neoforge-1.21.11-1.5.1.jar")
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
