java.version=17
minecraft.version=1.20.1

version.target.min=0.6.0-forge1.1.8

libs.parchment=2023.09.03
libs.fabric.api=0.92.7+1.20.1
libs.yacl=3.6.6+1.20.1-fabric
libs.tacz=1.20.1-0.6.0-forge1.1.8
# Forge Config API Port 8.0.3 (CurseForge file id)
libs.forge-config-api-port=7260491

libs.modmenu=7.2.2
libs.valkyrienskies=2.4.10
libs.valkyrienskies-core=1.1.0+1d4a7373e9
libs.sound-physics-remastered=fabric-1.20.1-1.5.1

libs.cubes-without-borders=3.0.0+1.20