java.version=21
minecraft.version=1.21.11

# q14433686-arch/TaCZ_Refabricated_Unofficial 1.21.11 R2.
# CurseForge project 1627909, file 8660664.
version.target.min=1.1.8

libs.fabric.api=0.141.6+1.21.11
libs.yacl=3.8.2+1.21.11-fabric
libs.tacz=8660664
libs.forge-config-api-port=21.11.1
libs.cloth-config=21.11.153

libs.modmenu=17.0.0
libs.sound-physics-remastered=fabric-1.21.11-1.5.1

libs.cubes-without-borders=3.0.0+1.21.11
