java.version=21
minecraft.version=1.21.1

version.target.min=0.6.0-forge1.1.8

libs.parchment=2024.11.17
libs.fabric.api=0.116.8+1.21.1
libs.yacl=3.8.2+1.21.1-fabric
libs.tacz=1.21.1-0.6.1-forge1.1.8
# Forge Config API Port 21.1.6 (CurseForge file id)
libs.forge-config-api-port=7213608

libs.modmenu=11.0.3
libs.sable=1.0.6
libs.sable-companion=1.4.2
libs.sound-physics-remastered=fabric-1.21.1-1.5.1

libs.cubes-without-borders=3.0.0+1.21
# 2.0.0
libs.keybind-fix-plus=jFW6823S